{"name": "test_search_in_python_org", "status": "broken", "statusDetails": {"message": "FileNotFoundError: [Errno 2] No such file or directory: 'send_invite.PNG'", "trace": "self = <Individual_Signup.test_invite testMethod=test_search_in_python_org>\n\n    def tearDown(self):\n        time.sleep(5)\n        self.driver.save_screenshot(\"idsig.png\")\n        screenshot = Image.open(\"idsig.png\")\n>       allure.attach.file(r\"send_invite.PNG\", \"screenshot\",attachment_type=allure.attachment_type.PNG)\n\nIndividual_Signup.py:518: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/allure_commons/_allure.py:182: in file\n    plugin_manager.hook.attach_file(source=source, name=name, attachment_type=attachment_type, extension=extension)\n/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/pluggy/_hooks.py:265: in __call__\n    return self._hookexec(self.name, self.get_hookimpls(), kwargs, firstresult)\n/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/pluggy/_manager.py:80: in _hookexec\n    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)\n/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/allure_pytest/listener.py:226: in attach_file\n    self.allure_logger.attach_file(uuid4(), source, name=name, attachment_type=attachment_type, extension=extension)\n/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/allure_commons/reporter.py:114: in attach_file\n    plugin_manager.hook.report_attached_file(source=source, file_name=file_name)\n/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/pluggy/_hooks.py:265: in __call__\n    return self._hookexec(self.name, self.get_hookimpls(), kwargs, firstresult)\n/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/pluggy/_manager.py:80: in _hookexec\n    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)\n/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/allure_commons/logger.py:53: in report_attached_file\n    shutil.copy2(source, destination)\n/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/shutil.py:434: in copy2\n    copyfile(src, dst, follow_symlinks=follow_symlinks)\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n\nsrc = 'send_invite.PNG'\ndst = '/Users/asadullahkhan/Desktop/AKRU-Scripts/Front-user/SIGNUPS/Login_report/634a7b13-7386-4e81-b134-39b5ab6036bb-attachment.png'\n\n    def copyfile(src, dst, *, follow_symlinks=True):\n        \"\"\"Copy data from src to dst in the most efficient way possible.\n    \n        If follow_symlinks is not set and src is a symbolic link, a new\n        symlink will be created instead of copying the file it points to.\n    \n        \"\"\"\n        sys.audit(\"shutil.copyfile\", src, dst)\n    \n        if _samefile(src, dst):\n            raise SameFileError(\"{!r} and {!r} are the same file\".format(src, dst))\n    \n        file_size = 0\n        for i, fn in enumerate([src, dst]):\n            try:\n                st = _stat(fn)\n            except OSError:\n                # File most likely does not exist\n                pass\n            else:\n                # XXX What about other special files? (sockets, devices...)\n                if stat.S_ISFIFO(st.st_mode):\n                    fn = fn.path if isinstance(fn, os.DirEntry) else fn\n                    raise SpecialFileError(\"`%s` is a named pipe\" % fn)\n                if _WINDOWS and i == 0:\n                    file_size = st.st_size\n    \n        if not follow_symlinks and _islink(src):\n            os.symlink(os.readlink(src), dst)\n        else:\n>           with open(src, 'rb') as fsrc:\nE           FileNotFoundError: [Errno 2] No such file or directory: 'send_invite.PNG'\n\n/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/shutil.py:254: FileNotFoundError"}, "attachments": [{"name": "screenshot", "source": "634a7b13-7386-4e81-b134-39b5ab6036bb-attachment.png", "type": "image/png"}, {"name": "log", "source": "4a33660b-62e7-4547-a5f8-dcb06bc8db41-attachment.txt", "type": "text/plain"}, {"name": "stdout", "source": "dee2485f-e324-4d60-bc0f-c1a6068eacc1-attachment.txt", "type": "text/plain"}, {"name": "stderr", "source": "d80a4723-9631-4f83-896a-035e924652a8-attachment.txt", "type": "text/plain"}], "start": 1658751760818, "stop": 1658752159206, "uuid": "2a09404b-47d4-4127-a7dd-c20c08736783", "historyId": "fec58d19cbf88f46bc0822ce50ec5d15", "testCaseId": "7bb646d53d763db557b8c21b9aac9770", "fullName": "Individual_Signup.test_invite#test_search_in_python_org", "labels": [{"name": "suite", "value": "Individual_Signup"}, {"name": "subSuite", "value": "test_invite"}, {"name": "host", "value": "Asads-MacBook-Pro.local"}, {"name": "thread", "value": "78723-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "Individual_Signup"}]}